### ISSUE TITLE
Variables inside translated string

### ISSUE THREAD

**Issue by mhaamann** [smhg/gettext-handlebars#8]
I have the following string that I would like to translate: 

`{{authorName}} has created '{{groupName}}' in your group.`

Variables would make the string render like this: `Matthias has created "Summerparty" in your group`

I tried the following, which didn't work:
`{{_ "{{authorName}} has created '{{groupName}}' in your group."}}`

Any ideas?

**Comment by smhg** [comment]
What do you mean with _didn't work_?
The variables' values didn't get replaced or you didn't get the translation?

**Comment by mhaamann** [comment]
Yes, the variables didn't get replaced

**Comment by smhg** [comment]
What should be parsed out by gettext-handlebars and end up in the result is:
`{{authorName}} has created '{{groupName}}' in your group.`
So I guess that works as expected.

You basically have 3 options to handle variable interpolation:
* Have your `_` block-helper handle it.
* Wrap the `_()` call in another helper which handles it.
* Handle it in whatever calls your template and pass the result to the template.

I would favour the last one. My opinion: these more advanced operations aren't things you should try to do in your template. Templates should be kept simple.

Does that make sense?

**Comment by mhaamann** [comment]
Yes it makes sense. Would just prefer to keep the strings inside the templates and not having to pre render them somewhere else.
